meeting:
  #phone 切片
  start_phone: 1
  end_phone: -1


data:
  token:
  userAccount: kangyao.xue@net263.com
  meetingTitle:
  startTime: 1656438600000
  duration: 120
  contactList: [
                {
                    "contactName": '',
                    "contactTelephone": '',
                    "contactEmail": ''
                }
            ]
  callOutType: 6
  hangUpSetting: 0
  hangUpDuration:
  isRecord: 1
  joinType: 0
  meetingExplain: "会议说明"
  subscribeHostStatus: 0
  subscribeGuestStatus: 0

data2:
  token:

data3:
  token: