meeting:
  start_phone_test: 0
  end_phone_test: 70

  #phone 切片
  start_phone: 0
  end_phone: 2000

  start_phone_650: 2000
  end_phone_650: 3500

  start_phone_2: 1100
  end_phone_2: 1700

  start_phone_3: 1700
  end_phone_3: 2300

  start_phone_4: 2300
  end_phone_4: 2900

  start_phone_5: 2900
  end_phone_5: 3500

  start_phone_6: 3500
  end_phone_6: -1

Mode:
    #共创建多少场畅听会议
    meeting_num_test: 5
    meeting_num: 350
    meeting_num_650: 650