meeting:
  #phone 切片
  start_phone: 1
  end_phone: -1

#倾听会议 接口参数

data:
  token:
  userAccount: kangyao.xue@net263.com
  meetingTitle:
  startTime: 1657702186000
  duration: 120
  contactList: [
                {
                    "contactName": '',
                    "contactTelephone": '',
                    "contactEmail": ''
                }
            ]
  callOutType: 6
  hangUpSetting: 0
  hangUpDuration:
  isRecord: 1
  joinType: 0
  meetingExplain: "会议说明"
  subscribeHostStatus: 0
  subscribeGuestStatus: 0

data2:
  token:

data3:
  token:

#畅听会议接口参数

sec_meeting_cx1:
  token:
  userAccount: cx1@net263.com
  meetingCode:
  meetingTitle:
  startTime: 1657791026000
  durationMinute: 120
  smsNoticeStatus: 1
  remindMinute: 15

sec_meeting_cx2:
  token:
  userAccount: cx2@net263.com
  meetingCode:
  meetingTitle:
  startTime: 1657791026000
  durationMinute: 120
  smsNoticeStatus: 1
  remindMinute: 15

sec_meeting_cx3:
  token:
  userAccount: cx3@net263.com
  meetingCode:
  meetingTitle:
  startTime: 1657791026000
  durationMinute: 120
  smsNoticeStatus: 1
  remindMinute: 15